// src/app/common/components/header/header.component.ts
import { Component, OnInit, Input } from '@angular/core';
// , ViewChild
import { Router, ActivatedRoute } from '@angular/router';

import {NgbModal, NgbModalRef} from '@ng-bootstrap/ng-bootstrap';
import { LoginService } from '../../services/login.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {


  constructor(private loginService: LoginService,
    private router: Router,
    private route: ActivatedRoute,
    private modalService: NgbModal  ) {}

  // ---- Login Modal
  private loginModalRef: NgbModalRef;

  openloginModal(content) {
    this.loginModalRef = this.modalService.open(content);
    this.loginModalRef.result.then((result) => { }, (reason) => { });
  }
  // ---- Login Modal

  // ----- FORM

  loginError: any = {
    status : false,
    type: 'success',
    message : 'Default text'
  };
	  

  login(loginForm){ 
    console.log('loginform ', loginForm);
       
    let returnData = this.loginService.checkUserLogin(loginForm.value)
    .subscribe( response => {
        console.log('== response - ', response, ' type of ', typeof response);
        
        if(response['token'] !== ''){
          this.loginError = {
            type : 'success',
            status: true,
            message: 'Logged In successfully'
          }
          this.loginSuccess();
        }        
    },
    (error: Response) => {
      this.loginError.type = 'danger';
      console.log('Unexpected error occured ', error);
      if(error.status === 401){
        this.loginError.message = "Either of you details is incorrect";
      }
      else{
        this.loginError.message = "An Unexpected error occured";
      }
      this.loginError.status = true;
    });
  }

  loginSuccess(){
    this.loginModalRef.close(); // closing modal

    this.changeHeaderMessage('success', 'You have logged in successfully');

    this.router.navigate(['/users/dashboard']);

  }
  
  log(data){
    // console.log(data);
  }

  // ------------- LOGIN

  // Main header alert message
  HeaderMessage = {
    type: '',
    message: ''
  }

  closeHeaderMessage(){
    this.HeaderMessage = null;    
  }

  changeHeaderMessage(type, message){
    this.HeaderMessage = { type: type, message: message }
    var self = this;
    setTimeout(function(){
      self.closeHeaderMessage();
    }, 5000);
  }


  ngOnInit() {
    // this.closeHeaderMessage();

    this.route.queryParamMap.subscribe((data)=>{
      // console.log('--- ', data);
      if(data.get('action') === 'signUpsuccess'){
        this.loginError = { status: true, type: 'success', message: 'Please login to continue' }
        this.changeHeaderMessage('success', 'Congratulations, you have been successfully registered, login to continue');
        // this.openloginModal(this.content);
      }
    });
  }



}

<header style="margin-bottom: 0px;" class="">
    <div class="container">
        <div class="row">
            <div class="col-md-4"> <img src="assets/images/Logo_SA.png" class="p-cursor" width="50px" alt="LOGO" routerLink="/"></div>
            <div class="col-md-8">
                <div class="header-ryt text-right">                    
                    <button type="button"  *ngIf="!loginService.isLoggedIn()" (click)="openloginModal(content)" class="btn btn-outline-primary btn-sm">Login</button>
                    <button type="button"routerLink="/users/sign-up" *ngIf="!loginService.isLoggedIn()" class="btn btn-outline-primary btn-sm">Register</button>

                    <div *ngIf="loginService.isLoggedIn()">
                        <div class="user-image" >
                            <span *ngIf="loginService.isLoggedIn()"> <span class="text-danger" >Welcome</span> {{userService.currentUser.user.fname}}</span>
                            <img src="assets/images/user.jpg" 
                                (click)="headerDropdown = !headerDropdown"
                            class="rounded-circle p-cursor" alt="user">
                        </div>
                        <ul *ngIf="headerDropdown" class="header-drp-dwn" >
                            <li><button routerLink="/users/dashboard" (click)="headerDropdown = !headerDropdown"
                                class="btn btn-light btn-block">Dashboard</button></li>
                            <li><button class="btn btn-light btn-block">Other</button></li>
                            <li><button (click)="headerDropdown = !headerDropdown"
                                 routerLink="/users/sign-up" (click)="loginService.logOut()"
                            class="btn btn-light btn-block">Logout</button></li>
                        </ul>
                    </div>
                    <!-- <button type="button" *ngIf="!loginService.isLoggedIn()" routerLink="/users/sign-up" (click)="loginService.logOut()" class="btn btn-outline-primary btn-sm">Logout</button> -->
                </div>
            </div>
        </div>
    </div>
</header>

<!-- ---------- NAV BAR ---------- -->

<nav *ngIf="loginService.isLoggedIn()" class="navbar navbar-expand-md bg-danger navbar-dash nav-dash">
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
    <button class="navbar-toggler" (click)="toggleMenuItems = !toggleMenuItems" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" [class.show-collapsed-menu]="toggleMenuItems" id="collapsibleNavbar">
        <div class="container">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" routerLink="/users/dashboard">Dashboard</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" routerLink="/users/property/new">Add New Property</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" routerLink="/users/property/search">Find Property</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" routerLink="/users/profile/edit">My Profile</a>
            </li>
        </ul>
        </div>
    </div>
</nav>

<!-- ---------- NAV BAR ---------- -->

<!-- ------------------ PAGE LOADER ---------------- -->
<app-page-loader [loaderActive] ="true" ></app-page-loader>
<!-- ------------------ PAGE LOADER ---------------- -->

<div *ngIf="HeaderMessage.message != ''" class="container header-message">
    <div class="alert alert-{{HeaderMessage.type}}" >{{HeaderMessage.message}}
        <button type="button" class="close" (click)="closeHeaderMessage()" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>


<!-- -------------- LOGIN MODAL ----------- -->

<ng-template #content *ngIf="!loginService.isLoggedIn()" let-c="close" let-d="dismiss">
    <div class="modal-header">
      <h4 class="modal-title">Sign In</h4>
      <button type="button" class="close" aria-label="Close" (click)="d('Cross click')">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">

        <div *ngIf="loginError.status" class="alert alert-{{ loginError.type }}">
            {{ loginError.message }}
        </div>

        <form #loginForm="ngForm" (ngSubmit)="login(loginForm)"  >
            <div class="form-group">
                <label for="">Email / Phone Number</label>
                <input ngModel name="emailPhno" type="text" #emailPhno="ngModel" (change)="log(emailPhno)"  class="form-control" required >
                <small class="text-danger"
                    *ngIf="emailPhno.touched && emailPhno.invalid"  >
                This field is required</small>
            </div>
            <div class="form-group">
                <label for="">Password</label>
                <input ngModel type="password" name="loginPassword" #loginPassword="ngModel" (change)="log(loginPassword)" class="form-control" required >
                <small class="text-danger"
                    *ngIf="loginPassword.touched && loginPassword.invalid"  >
                This field is required</small>
            </div>
            <div class="form-group">
                <button class="btn btn-success form-control" [disabled]="!loginForm.valid" >Login</button>
            </div>
        </form>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-outline-dark" (click)="c('Close click')">Close</button>
    </div>
</ng-template>
  
  <!-- -------------- LOGIN MODAL ----------- -->

// REACT_CODE_BASE/src/components/common/header.jsx
import React from "react";
import { Link } from "react-router-dom";
import Form from "./form";
import { Dropdown, Alert } from "react-bootstrap";

import LOGO from "../../assets/images/Logo_SA.png";
import userImg from "../../assets/images/user.jpg";
import * as authService from "../../services/authService";
import LoginModal from "../auth/loginModal";
import Navbar from "./navbar";
import CommonUIAddons from "./commonAddons";
import queryString from "query-string";

var togglePageLoaderFlag = false;

class Header extends Form {
  state = {
    loginModalToggle: false,
    navItems: [
      { path: "/users/dashboard", name: "Dashboard" },
      { path: "/property/new", name: "Add New Property" },
      { path: "/property/search", name: "Find Property" },
      { path: "/property/listing/", name: "My Listing" },
      { path: "/users/profile", name: "My Profile" }
    ],
    alertNotification: {
      status: false,
      message: "",
      variant: ""
    }
  };

  componentDidUpdate() {
    const queryParams = queryString.parse(this.props.location.search);
    if (queryParams) {
      // ============= NEW USER ===============
      if (
        queryParams.action === "signUpsuccess" &&
        queryParams.modal === "open"
      ) {
        this.setState({
          alertNotification: {
            status: true,
            message: "Congratulations! You have registered successfully..",
            variant: "success"
          }
        });
        this.toggleLoginModal();
      }
      // =============== LOGOUT ===================
      else if (
        queryParams.action === "logOut" &&
        queryParams.control === "completed"
      ) {
        this.refineQueryParams();

        this.setState({
          alertNotification: {
            status: true,
            message: "You have logged out successfully..",
            variant: "primary"
          }
        });
      }
      // ============== PROTECTED URL =============
      else if (queryParams.redirectUrl && queryParams.modal === "open") {
        this.toggleLoginModal();

        this.setState({
          alertNotification: {
            status: true,
            message: "Kindly login to continue..",
            variant: "info"
          }
        });
      }
    }
  }

  refineQueryParams = () => {
    const queryParams = queryString.parse(this.props.location.search);
    if (queryParams) {
      if (queryParams.modal === "open") delete queryParams.modal;
      if (queryParams.control === "completed") delete queryParams.control;

      const stringified = queryString.stringify(queryParams);
      // console.log(stringified);
      this.props.history.push(`?${stringified}`);
    }
  };

  toggleLoginModal = () => {
    this.refineQueryParams();

    let loginModalToggle = this.state.loginModalToggle;
    loginModalToggle = !loginModalToggle;
    this.setState({ loginModalToggle });
  };

  setLoggedInUser = user => {
    this.setState({ user });
  };

  handleLogout = () => {
    const isLoggedOut = authService.logOut();
    if (isLoggedOut) window.location = "/?action=logOut&control=completed";
  };

  handleAlertDismiss = () => {
    this.setState({
      alertNotification: { status: false, message: "", variant: " " }
    });
  };

  render() {
    const { loginModalToggle, navItems, alertNotification } = this.state;
    const { user } = this.props;
    return (
      <React.Fragment>
        <header style={{ marginBottom: "0px" }} className="">
          <div className="container">
            <div className="row">
              <div className="col-md-4">
                <Link to="/">
                  <img
                    src={LOGO}
                    className="p-cursor"
                    width="50px"
                    alt="LOGO"
                  />
                </Link>
              </div>
              <div className="col-md-8">
                <div className="header-ryt text-right">
                  {/* <!-- <a routerLink="/" >Home</a>                  
                            <a routerLink="/" >Find Property</a> --> */}
                  {!user && (
                    <React.Fragment>
                      <button
                        type="button"
                        style={{ marginRight: "5px" }}
                        className="btn btn-outline-primary btn-sm"
                        onClick={this.toggleLoginModal}
                      >
                        Login
                      </button>
                      <Link
                        to="/sign-up"
                        className="btn btn-outline-primary btn-sm"
                      >
                        Register
                      </Link>
                    </React.Fragment>
                  )}
                  {user && (
                    <div className="user-image">
                      <Dropdown alignRight>
                        <Dropdown.Toggle variant="" id="dropdown-basic">
                          <span>
                            <span className="text-danger">Welcome </span> &nbsp;
                            {(user && user.fname) || ""}
                          </span>
                          &nbsp;
                          <img
                            src={userImg}
                            className="rounded-circle p-cursor"
                            alt="user"
                            width="50px"
                          />
                        </Dropdown.Toggle>
                        <Dropdown.Menu>
                          {user && user.isAdmin && (
                            <Dropdown.Item href="/admin">
                              {/* <Link
                                to="/admin"
                                className="btn btn-light btn-block"
                              >
                              </Link> */}
                              Admin Dashboard
                            </Dropdown.Item>
                          )}
                          <Dropdown.Item>
                            <button
                              onClick={this.handleLogout}
                              className="btn btn-light btn-block"
                            >
                              Logout
                            </button>
                          </Dropdown.Item>
                        </Dropdown.Menu>
                      </Dropdown>
                    </div>
                    // <mat-menu #headerRytmenu="matMenu" xPosition="before">
                    //       <button routerLink="/users/dashboard" mat-menu-item>Dashboard</button>
                    //       <button *ngIf="userService.currentUser?.user.isAdmin" routerLink="/admin/dashboard" mat-menu-item>Admin</button>
                    //       <button (click)="loginService.logOut()" mat-menu-item>Logout</button>
                    //   </mat-menu>
                  )}
                </div>
              </div>
            </div>
          </div>
        </header>

        {/* ---------------------- LOGIN MODAL ----------------------------- */}
        <LoginModal
          toggle={loginModalToggle}
          toggleLoginModal={this.toggleLoginModal}
          setLoggedInUser={this.setLoggedInUser}
          {...this.props}
        />
        {/* ---------------------- LOGIN MODAL ----------------------------- */}
        {user && <Navbar navItems={navItems} />}
        <CommonUIAddons pageLoaderFlag={togglePageLoaderFlag} />

        {/* =================== ALERT MESSAGE =================== */}
        {alertNotification.status && (
          <div className="container mt-3">
            <Alert
              variant={alertNotification.variant}
              onClose={this.handleAlertDismiss}
              dismissible
            >
              {alertNotification.message}
            </Alert>
          </div>
        )}
        {/* =================== ALERT MESSAGE =================== */}
      </React.Fragment>
    );
  }
}

export const togglePageLoader = () => {
  togglePageLoaderFlag = !togglePageLoaderFlag;
};

export default Header;
