// REACT_CODE_BASE/src/components/property/findProperty.jsx
import React, { Component } from "react";
import * as commonService from "../../services/commonServices";
import PropertyList from "../common/propertyList";
import queryString from "query-string";
import { OverlayTrigger, Tooltip } from "react-bootstrap";

import "../../assets/styles/property.css";

class FindProperty extends Component {
  state = {
    propertyTypeList: [],
    cityList: [],
    queryParams: "?status=available",
    blockSize: 6,
    filterData: {
      propertyFor: [],
      type: [],
      city: []
    },
    toggleType: {
      type: "",
      status: false
    }
  };

  async componentDidMount() {
    const { data: propertyTypeList } = await commonService.get(
      "/property/type"
    );

    let cityList = await commonService.renderCityList("");

    cityList = cityList.slice(1);

    this.setState({ propertyTypeList, cityList });
  }

  capitalizeText = val => {
    if (!val) return "";
    return val.charAt(0).toUpperCase() + val.slice(1);
  };

  toggleBlockSize = blockSize => {
    this.setState({ blockSize });
  };

  toggleSwitch = toggleType => {
    this.setState({ toggleType });
  };

  manageCheckedValue = (value, location, checked) => {
    // console.log(value, location, checked);
    const filterData = { ...this.state.filterData };

    if (checked) filterData[location].push(value);
    else {
      const index = filterData[location].indexOf(value);
      if (index > -1) filterData[location].splice(index, 1);
    }
    this.setState({ filterData });
  };

  filterProperties = () => {
    const { filterData } = this.state;
    const stringifiedString = queryString.stringify(filterData);

    let queryParams = queryString.stringify(filterData, {
      arrayFormat: "comma"
    });
    queryParams = queryParams
      ? `?${queryParams}&status=available`
      : `?status=available`;

    this.setState({ queryParams });
    this.props.history.push(`?${stringifiedString}`);
  };

  setPropCount = count => {
    console.log("==========", count);
    this.setState({ count });
  };

  clearFilters = () => {
    window.location = "/property/search";
    // this.setState({
    //   queryParams: "",
    //   filterData: {
    //     propertyFor: [],
    //     type: [],
    //     city: []
    //   }
    // });
    // this.props.history.push("/property/search");
  };

  render() {
    const {
      propertyTypeList,
      cityList,
      queryParams,
      blockSize,
      count
    } = this.state;

    return (
      <React.Fragment>
        <div className="container">
          <div className="row">
            <div className="col-md-3">
              <div className="filterBox">
                <h4>
                  Filters
                  <a
                    href="javascript:void(0);"
                    onClick={this.clearFilters}
                    className="text-info clickable"
                  >
                    <small> clear</small>
                  </a>
                  <button
                    onClick={this.filterProperties}
                    className="btn btn-danger btn-sm float-right"
                  >
                    Search
                  </button>
                </h4>
                <div className="card pt-4 pb-3 pl-3 pr-3 mb-4">
                  <h5>
                    Property For:
                    <i className="fa fa-plus-square-o float-right" />
                    {/* onClick={() => this.toggleSwitch({ "propertyFor",  })}  */}
                  </h5>
                  <hr className="hr" />
                  <div className="row pl-3">
                    {[
                      { key: "sell", val: "buy" },
                      { key: "rent", val: "rent" }
                    ].map((ele, index) => (
                      <div
                        key={"customCheck" + index}
                        className="custom-control custom-checkbox col"
                      >
                        <input
                          type="checkbox"
                          className="custom-control-input"
                          value={ele.val}
                          onChange={event =>
                            this.manageCheckedValue(
                              ele.val,
                              "propertyFor",
                              event.currentTarget.checked
                            )
                          }
                          id={"customCheck" + index}
                        />
                        <label
                          className="custom-control-label clickable"
                          htmlFor={"customCheck" + index}
                        >
                          {this.capitalizeText(ele.key)}
                        </label>
                      </div>
                    ))}
                  </div>
                  <div className="mt-3">
                    <h5>
                      Property Type:
                      <i className="fa fa-plus-square-o float-right" />
                    </h5>
                    <hr className="hr" />
                    <div className="optionsBlock">
                      {propertyTypeList.map((ele, index) => (
                        <div
                          key={"customPropType" + index}
                          className="custom-control custom-checkbox col"
                        >
                          <input
                            type="checkbox"
                            className="custom-control-input"
                            value={ele._id}
                            onChange={event =>
                              this.manageCheckedValue(
                                ele._id,
                                "type",
                                event.currentTarget.checked
                              )
                            }
                            id={"customPropType" + index}
                          />
                          <label
                            className="custom-control-label clickable"
                            htmlFor={"customPropType" + index}
                          >
                            {this.capitalizeText(ele.title)}
                          </label>
                        </div>
                      ))}
                    </div>
                  </div>
                  <div className="mt-3">
                    <h5>
                      City:
                      <i className="fa fa-plus-square-o float-right" />
                    </h5>
                    <hr className="hr" />
                    <div className="optionsBlock">
                      {cityList.map((ele, index) => (
                        <div
                          key={"customCityName" + index}
                          className="custom-control custom-checkbox col"
                        >
                          <input
                            type="checkbox"
                            className="custom-control-input"
                            value={ele._id}
                            onChange={event =>
                              this.manageCheckedValue(
                                ele._id,
                                "city",
                                event.currentTarget.checked
                              )
                            }
                            id={"customCityName" + index}
                          />
                          <label
                            className="custom-control-label clickable"
                            htmlFor={"customCityName" + index}
                          >
                            {this.capitalizeText(ele.name)}
                          </label>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-9 filteredPropertyBox">
              <div className="row">
                <div className="col-3">Showing {count} properties</div>
                <div className="col-5">
                  <OverlayTrigger
                    key="top"
                    placement="top"
                    overlay={
                      <Tooltip>
                        To view your properties head to My Listing tab
                      </Tooltip>
                    }
                  >
                    <h5 variant="secondary" className="text-center">
                      Your properties will not list here
                    </h5>
                  </OverlayTrigger>
                </div>
                <div className="col-4 text-right">
                  <button
                    type="button"
                    onClick={() => this.toggleBlockSize(12)}
                    className="btn btn-danger btn-sm"
                  >
                    <i className="fa fa-list" aria-hidden="true" />
                  </button>
                  <button
                    type="button"
                    onClick={() => this.toggleBlockSize(6)}
                    className="btn btn-danger btn-sm ml-1"
                  >
                    <i className="fa fa-th-large" aria-hidden="true" />
                  </button>
                </div>
              </div>
              <PropertyList
                queryParams={queryParams}
                blockSize={blockSize}
                listingCount={count => this.setPropCount(count)}
                notUserId={true}
                {...this.props}
              />
            </div>
          </div>
        </div>
      </React.Fragment>
    );
  }
}

export default FindProperty;

// ANGULAR_CODE_BASE/src/app/features/property/find-property/find-property.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { CommonService } from '../../../common/services/common.service';

@Component({
  selector: 'app-find-property',
  templateUrl: './find-property.component.html',
  styleUrls: ['./find-property.component.scss']
})
export class FindPropertyComponent implements OnInit {

  constructor(
    private commonService: CommonService,
    private route: Router,
    private activatedRoute: ActivatedRoute
  ) { }

  propertyTypeList = [];
  cityList = [];
  propertyList = [];
  blockView = { status: true, size: 6 };
  queryParams = '?status=available';
  filterData = {
    propertyFor: [],
    type: [],
    city: []
  };

  SidebarHiddenItem = 0;

  hideSidebarItem(num) {
    if (this.SidebarHiddenItem == num)
      this.SidebarHiddenItem = 0;
    else
      this.SidebarHiddenItem = num;
  }

  manageCheckedValue(value, location, checked) {
    if (checked) {
      this.filterData[location].push(value);
    }
    else {
      let index = this.filterData[location].indexOf(value);
      if (index > -1) {
        this.filterData[location].splice(index, 1);
      }
    }
  }

  filterProperties(data = '') {
    // var tempVar = Object.values(this.filterData).filter(e => e.length);
    // if (tempVar.length) {
      this.route.navigate([window.location.pathname], {
        queryParams: this.filterData
      });
      data += '?status=available';
      (this.filterData.propertyFor.length) ? data += '&propertyFor=' + this.filterData.propertyFor : '';
      (this.filterData.type.length) ? data += '&type=' + this.filterData.type : '';
      (this.filterData.city.length) ? data += '&city=' + this.filterData.city : '';
      this.queryParams = data;
    // }
  }

  uncheckAll;
  clearFilters() {
    this.route.navigate([window.location.pathname]);
    this.uncheckAll = false;
    this.queryParams = '';
  }

  log(data) {
    console.log('log fn ', data);
  }

  checkCheckedValue(value, type){
    if(value && this.filterData[type]){
      var tempVar = this.filterData[type].filter(ele => ele == value)
      return tempVar.length ? true : false;
    }
    else return false;
  }

  ngOnInit() {
    this.commonService.getPropertyTypeList()
      .subscribe(result => {
        this.propertyTypeList = result;
      });

    this.commonService.getCitylist()
      .subscribe(result => {
        this.cityList = result;
      });
    
    this.activatedRoute.queryParamMap
    .subscribe(ele => {
      this.filterData.propertyFor = JSON.parse(JSON.stringify(ele.getAll('propertyFor')));
      this.filterData.type = JSON.parse(JSON.stringify(ele.getAll('type')));
      this.filterData.city = JSON.parse(JSON.stringify(ele.getAll('city')));
    });
  }
}

<div class="container find-properties">
  <div class="row">
    <div class="col-md-3">
      <form #filter="ngForm" class="positn-sticky" (ngSubmit)="filterProperties()">
        <h4>
          <i class="fa fa-filter" aria-hidden="true"></i> Filters
          <a href="javascript:void(0);" (click)="clearFilters()">
            <small>clear</small>
          </a>
          <button class="btn btn-success btn-sm float-right">Search</button>
        </h4>
        <div class="border-main border-box-manage side-bar-filter card">
          <div class="form-group">
            <h5>Property For:
              <i (click)="hideSidebarItem(1);" [ngClass]="{ 
              'fa-plus-square-o': SidebarHiddenItem == 1,
              'fa-minus-square-o': SidebarHiddenItem != 1
             }" class="fa  p-cursor float-right" aria-hidden="true"></i>
            </h5>
            <hr class="hr">
            <div class="custom-control custom-checkbox" [hidden]="SidebarHiddenItem == 1">
              <div class="row">
                <div
                  *ngFor="let propertyFor of [{ key: 'sell', val: 'buy'}, { key: 'rent', val: 'rent'}];let loop = index"
                  class="col">
                  <input name="propertyFor" type="checkbox" class="custom-control-input" id="forCheck{{loop}}"
                    value="{{propertyFor.key}}" [checked]="checkCheckedValue(propertyFor.key, 'propertyFor')"
                    (change)="$event.target.checked? manageCheckedValue(propertyFor.key, 'propertyFor', true) : manageCheckedValue(propertyFor.key, 'propertyFor', false)">
                  <label class="custom-control-label" style="padding-left: 5px;"
                    for="forCheck{{loop}}">{{propertyFor.val | titlecase }}</label>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group">
            <h5>Property Type:
              <i (click)="hideSidebarItem(2);" [ngClass]="{ 
              'fa-plus-square-o': SidebarHiddenItem == 2,
              'fa-minus-square-o': SidebarHiddenItem != 2
             }" class="fa  p-cursor float-right" aria-hidden="true"></i>
            </h5>
            <hr class="hr">
            <div [hidden]="SidebarHiddenItem == 2" class="options-block">
              <div *ngFor="let type of propertyTypeList; let loop = index"
                class="custom-control custom-checkbox d-block">
                <input name="type" type="checkbox" class="custom-control-input" id="customCheck{{loop}}"
                  value="{{type._id}}" [checked]="checkCheckedValue(type._id, 'type')"
                  (change)="$event.target.checked? manageCheckedValue(type._id, 'type', true) : manageCheckedValue(type._id, 'type', false)">
                <label class="custom-control-label" for="customCheck{{loop}}">{{type.title}}</label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <h5>City:
              <i (click)="hideSidebarItem(3);" [ngClass]="{ 
              'fa-plus-square-o': SidebarHiddenItem == 3,
              'fa-minus-square-o': SidebarHiddenItem != 3
             }" class="fa p-cursor float-right" aria-hidden="true"></i>
            </h5>
            <hr class="hr">
            <div [hidden]="SidebarHiddenItem == 3" class="options-block">
              <!-- <label class="d-block" *ngFor="let city of cityList" >
                <input name="city" [value]="city._id" type="checkbox"
                (change)="$event.target.checked? manageCheckedValue(city._id, 'city', true) : manageCheckedValue(city._id, 'city', false)" > {{city.name}}
              </label>  -->
              <!-- #city="ngModel" ngModel -->
              <div *ngFor="let city of cityList; let loop = index" class="custom-control custom-checkbox d-block">
                <input name="type" type="checkbox" class="custom-control-input" id="cityCheck{{loop}}"
                  value="{{city._id}}" [checked]="checkCheckedValue(city._id, 'city')"
                  (change)="$event.target.checked? manageCheckedValue(city._id, 'city', true) : manageCheckedValue(city._id, 'city', false)">
                <label class="custom-control-label" for="cityCheck{{loop}}">{{city.name}}</label>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-9">
      <div class="pad-btm-15">
        <div class="row">
          <div class="col-md-7 text-right">
            <b>--Your properties will not show here--
              <app-small-components [componentName]="'moreInfoQstnMark'"
                [toolTipData]="{ position: 'right', text: 'Head to `My Listing tab` to see your properties' }">
              </app-small-components>
            </b>
          </div>
          <div class="col-md-5">
            <div class="text-right">
              <!-- {{ filter.value | json }} {{ filter.status }} -->
              <button [class.btn-danger]="!blockView.status" (click)="blockView = { status: false, size: 12 };"
                class="btn">
                <i class="fa fa-list" aria-hidden="true"></i>
              </button>
              <button [class.btn-danger]="blockView.status" (click)="blockView = { status: true, size: 6 }; "
                class="btn mar-left-10">
                <i class="fa fa-th-large" aria-hidden="true"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- <div class="border-main border-box-manage"> -->
      <app-propertylist [queryParams]="queryParams" [blockSize]="blockView.size" [hideOwnProperty]="true"
        [blockView]="blockView.status"></app-propertylist>
      <!-- </div> -->
    </div>
  </div>
</div>
