// src/app/features/users/components/property/find-property/find-property.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonService } from '../../../../../common/services/common.service';
import { HttpParams } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
  selector: 'app-find-property',
  templateUrl: './find-property.component.html',
  styleUrls: ['./find-property.component.scss']
})
export class FindPropertyComponent implements OnInit {

  constructor(
    private commonService: CommonService,
    private route: Router
  ) { }

  propertyTypeList = [];
  cityList = [];
  propertyList = [];
  blockView = true;

  filterData = {
    propertyFor: [],
    type: [],
    city: []
  }

  manageCheckedValue(value, location, checked){
    // console.log('values: ', value, location, checked);    
    if(checked){
      this.filterData[location].push(value);
      // console.log('ss ', this.filterData[location]);
    }
    else{
      let index = this.filterData[location].indexOf(value);
      if(index > -1){
        this.filterData[location].splice(index, 1);
        // console.log('sdfd', this.filterData[location], ' index ', index);
      }      
    }    
  }

  filterProperties(data = ''){
    this.route.navigate([window.location.pathname], {
      queryParams: this.filterData //{ as: 'xcvx', dfd: 'dsfsf' }
    })
    if (this.filterData.propertyFor.length > 0)
      data = data + '/?propertyFor='+this.filterData.propertyFor;
    if (this.filterData.type.length > 0)
      data = data + '&type='+this.filterData.type;
    if (this.filterData.city.length > 0)
      data = data + '&city='+this.filterData.city;
    // let dat = '/propertyFor/'+this.filterData.propertyFor+'/type/'+this.filterData.type+'/city/'+this.filterData.city;
    console.log(data);
    this.commonService.filterProperties(data)
    .subscribe(result => {
      console.log(result);      
    })
    // var params = new HttpParams()
    // .set('page', '2')
    // .set('page', '3')
  }

  log(data){
    console.log(data);    
  }

  ngOnInit() {
    this.commonService.getPropertyTypeList()
      .subscribe(result => {
        this.propertyTypeList = result;
      });

    this.commonService.getCitylist()
      .subscribe(result => {
        this.cityList = result;
      });
  }

}

<div class="container find-properties">
  <div class="row">
    <div class="col-md-3">
      <form #filter="ngForm" (ngSubmit)="filterProperties(e)" >
        <div class="border-main border-box-manage side-bar-filter">
          <h4><i class="fa fa-filter" aria-hidden="true"></i> Filters <button class="btn btn-success  btn-sm float-right">Search</button></h4>

          <div class="form-group">
            <h5 >Property For:</h5>
            <hr class="hr">
            <label>
              <input [value]="sell" type="checkbox" name="propertyFor" required
               (change)="$event.target.checked? manageCheckedValue('sell', 'propertyFor', true) : manageCheckedValue('sell', 'propertyFor', false)" > Sell
            </label> &nbsp;
            <label>
              <input [value]="rent" type="checkbox" name="propertyFor" required
                (change)="$event.target.checked? manageCheckedValue('rent', 'propertyFor', true) : manageCheckedValue('rent', 'propertyFor', false)" > Rent
            </label> &nbsp;
          </div>
          <div class="form-group">
            <h5 >Property Type:</h5>
            <hr class="hr">
            <div class="options-block">
              <label class="d-block" *ngFor="let type of propertyTypeList" >
                <input  name="type" type="checkbox" value="{{type._id}}" required
                (change)="$event.target.checked? manageCheckedValue(type._id, 'type', true) : manageCheckedValue(type._id, 'type', false)" > {{type.title}}
              </label> 
            </div>
          </div>
          <div class="form-group">
            <h5>City:</h5>
            <hr class="hr">
            <div class="options-block">
              <label class="d-block" *ngFor="let city of cityList" >
                <input name="city" value="city._id" type="checkbox"
                (change)="$event.target.checked? manageCheckedValue(city._id, 'city', true) : manageCheckedValue(city._id, 'city', false)" > {{city.name}}
              </label> 
            </div>
          </div>
        </div>
      </form>
    </div>
    <div class="col-md-9">
      <p>{{ filter.value | json }} {{ filter.status }}</p>
      <div class="text-right">
        <button [class.btn-danger]="!blockView" (click)="blockView = false;" class="btn"><i class="fa fa-list" aria-hidden="true"></i></button>
        <button [class.btn-danger]="blockView" (click)="blockView = true;" class="btn"><i class="fa fa-th-large" aria-hidden="true"></i></button>
      </div>
      <div class="border-main border-box-manage">
          <app-propertylist [queryParams]="queryParams" [blockView]="blockView" ></app-propertylist>
      </div>
    </div>
  </div>
</div>

// REACT_CODE_BASE/src/components/property/findProperty.jsx
import React, { Component } from "react";
import * as commonService from "../../services/commonServices";
import PropertyList from "../common/propertyList";
import queryString from "query-string";

import "../../assets/styles/property.css";

class FindProperty extends Component {
  state = {
    propertyTypeList: [],
    cityList: [],
    queryParams: "?status=available",
    blockSize: 6,
    filterData: {
      propertyFor: [],
      type: [],
      city: []
    },
    toggleType: {
      type: "",
      status: false
    }
  };

  async componentDidMount() {
    const { data: propertyTypeList } = await commonService.get(
      "/property/type"
    );

    let cityList = await commonService.renderCityList("");

    cityList = cityList.slice(1);

    this.setState({ propertyTypeList, cityList });
  }

  capitalizeText = val => {
    if (!val) return "";
    return val.charAt(0).toUpperCase() + val.slice(1);
  };

  toggleBlockSize = blockSize => {
    this.setState({ blockSize });
  };

  toggleSwitch = toggleType => {
    this.setState({ toggleType });
  };

  manageCheckedValue = (value, location, checked) => {
    // console.log(value, location, checked);
    const filterData = { ...this.state.filterData };

    if (checked) filterData[location].push(value);
    else {
      const index = filterData[location].indexOf(value);
      if (index > -1) filterData[location].splice(index, 1);
    }
    this.setState({ filterData });
  };

  filterProperties = () => {
    const { filterData } = this.state;
    const stringifiedString = queryString.stringify(filterData);

    let queryParams = queryString.stringify(filterData, {
      arrayFormat: "comma"
    });
    queryParams = queryParams
      ? `?${queryParams}&status=available`
      : `?status=available`;

    this.setState({ queryParams });
    this.props.history.push(`?${stringifiedString}`);
  };

  clearFilters = () => {
    window.location = "/property/search";
    // this.setState({
    //   queryParams: "",
    //   filterData: {
    //     propertyFor: [],
    //     type: [],
    //     city: []
    //   }
    // });
    // this.props.history.push("/property/search");
  };

  render() {
    const { propertyTypeList, cityList, queryParams, blockSize } = this.state;

    return (
      <React.Fragment>
        <div className="container">
          <div className="row">
            <div className="col-md-3">
              <div className="filterBox">
                <h4>
                  Filters
                  <a
                    onClick={this.clearFilters}
                    className="text-info clickable"
                  >
                    <small> clear</small>
                  </a>
                  <button
                    onClick={this.filterProperties}
                    className="btn btn-danger btn-sm float-right"
                  >
                    Search
                  </button>
                </h4>
                <div className="card pt-4 pb-3 pl-3 pr-3 mb-4">
                  <h5>
                    Property For:
                    <i className="fa fa-plus-square-o float-right" />
                    {/* onClick={() => this.toggleSwitch({ "propertyFor",  })}  */}
                  </h5>
                  <hr className="hr" />
                  <div className="row pl-3">
                    {[
                      { key: "sell", val: "buy" },
                      { key: "rent", val: "rent" }
                    ].map((ele, index) => (
                      <div
                        key={"customCheck" + index}
                        className="custom-control custom-checkbox col"
                      >
                        <input
                          type="checkbox"
                          className="custom-control-input"
                          value={ele.val}
                          onChange={event =>
                            this.manageCheckedValue(
                              ele.val,
                              "propertyFor",
                              event.currentTarget.checked
                            )
                          }
                          id={"customCheck" + index}
                        />
                        <label
                          className="custom-control-label clickable"
                          htmlFor={"customCheck" + index}
                        >
                          {this.capitalizeText(ele.key)}
                        </label>
                      </div>
                    ))}
                  </div>
                  <div className="mt-3">
                    <h5>
                      Property Type:
                      <i className="fa fa-plus-square-o float-right" />
                    </h5>
                    <hr className="hr" />
                    <div className="optionsBlock">
                      {propertyTypeList.map((ele, index) => (
                        <div
                          key={"customPropType" + index}
                          className="custom-control custom-checkbox col"
                        >
                          <input
                            type="checkbox"
                            className="custom-control-input"
                            value={ele._id}
                            onChange={event =>
                              this.manageCheckedValue(
                                ele._id,
                                "type",
                                event.currentTarget.checked
                              )
                            }
                            id={"customPropType" + index}
                          />
                          <label
                            className="custom-control-label clickable"
                            htmlFor={"customPropType" + index}
                          >
                            {this.capitalizeText(ele.title)}
                          </label>
                        </div>
                      ))}
                    </div>
                  </div>
                  <div className="mt-3">
                    <h5>
                      City:
                      <i className="fa fa-plus-square-o float-right" />
                    </h5>
                    <hr className="hr" />
                    <div className="optionsBlock">
                      {cityList.map((ele, index) => (
                        <div
                          key={"customCityName" + index}
                          className="custom-control custom-checkbox col"
                        >
                          <input
                            type="checkbox"
                            className="custom-control-input"
                            value={ele._id}
                            onChange={event =>
                              this.manageCheckedValue(
                                ele._id,
                                "city",
                                event.currentTarget.checked
                              )
                            }
                            id={"customCityName" + index}
                          />
                          <label
                            className="custom-control-label clickable"
                            htmlFor={"customCityName" + index}
                          >
                            {this.capitalizeText(ele.name)}
                          </label>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-9 filteredPropertyBox">
              <div className="row">
                <div className="col-8">
                  <h5 className="text-center">
                    Your properties will not list here
                  </h5>
                </div>
                <div className="col-4 text-right">
                  <button
                    type="button"
                    onClick={() => this.toggleBlockSize(12)}
                    className="btn btn-danger btn-sm"
                  >
                    <i className="fa fa-list" aria-hidden="true" />
                  </button>
                  <button
                    type="button"
                    onClick={() => this.toggleBlockSize(6)}
                    className="btn btn-danger btn-sm ml-1"
                  >
                    <i className="fa fa-th-large" aria-hidden="true" />
                  </button>
                </div>
              </div>
              <PropertyList
                // togglePageLoader={this.props.togglePageLoader}
                queryParams={queryParams}
                blockSize={blockSize}
                {...this.props}
              />
            </div>
          </div>
        </div>
      </React.Fragment>
    );
  }
}

export default FindProperty;
