// REACT_CODE_BASE/src/components/common/header.jsx
import React from "react";
import { Link } from "react-router-dom";
import Form from "./form";
import { Dropdown, Alert } from "react-bootstrap";

import LOGO from "../../assets/images/Logo_SA.png";
import userImg from "../../assets/images/user.jpg";
import * as authService from "../../services/authService";
import LoginModal from "../auth/loginModal";
import Navbar from "./navbar";
import CommonUIAddons from "./commonAddons";
import queryString from "query-string";

var togglePageLoaderFlag = false;

class Header extends Form {
  state = {
    loginModalToggle: false,
    navItems: [
      { path: "/users/dashboard", name: "Dashboard" },
      { path: "/property/new", name: "Add New Property" },
      { path: "/property/search", name: "Find Property" },
      { path: "/property/listing/", name: "My Listing" },
      { path: "/users/profile", name: "My Profile" }
    ],
    alertNotification: {
      status: false,
      message: "",
      variant: ""
    }
  };

  componentDidUpdate() {
    const queryParams = queryString.parse(this.props.location.search);
    if (queryParams) {
      // ============= NEW USER ===============
      if (
        queryParams.action === "signUpsuccess" &&
        queryParams.modal === "open"
      ) {
        this.setState({
          alertNotification: {
            status: true,
            message: "Congratulations! You have registered successfully..",
            variant: "success"
          }
        });
        this.toggleLoginModal();
      }
      // =============== LOGOUT ===================
      else if (
        queryParams.action === "logOut" &&
        queryParams.control === "completed"
      ) {
        this.refineQueryParams();

        this.setState({
          alertNotification: {
            status: true,
            message: "You have logged out successfully..",
            variant: "primary"
          }
        });
      }
      // ============== PROTECTED URL =============
      else if (queryParams.redirectUrl && queryParams.modal === "open") {
        this.toggleLoginModal();

        this.setState({
          alertNotification: {
            status: true,
            message: "Kindly login to continue..",
            variant: "info"
          }
        });
      }
    }
  }

  refineQueryParams = () => {
    const queryParams = queryString.parse(this.props.location.search);
    if (queryParams) {
      if (queryParams.modal === "open") delete queryParams.modal;
      if (queryParams.control === "completed") delete queryParams.control;

      const stringified = queryString.stringify(queryParams);
      // console.log(stringified);
      this.props.history.push(`?${stringified}`);
    }
  };

  toggleLoginModal = () => {
    this.refineQueryParams();

    let loginModalToggle = this.state.loginModalToggle;
    loginModalToggle = !loginModalToggle;
    this.setState({ loginModalToggle });
  };

  setLoggedInUser = user => {
    this.setState({ user });
  };

  handleLogout = () => {
    const isLoggedOut = authService.logOut();
    if (isLoggedOut) window.location = "/?action=logOut&control=completed";
  };

  handleAlertDismiss = () => {
    this.setState({
      alertNotification: { status: false, message: "", variant: " " }
    });
  };

  render() {
    const { loginModalToggle, navItems, alertNotification } = this.state;
    const { user } = this.props;
    return (
      <React.Fragment>
        <header style={{ marginBottom: "0px" }} className="">
          <div className="container">
            <div className="row">
              <div className="col-md-4">
                <Link to="/">
                  <img
                    src={LOGO}
                    className="p-cursor"
                    width="50px"
                    alt="LOGO"
                  />
                </Link>
              </div>
              <div className="col-md-8">
                <div className="header-ryt text-right">
                  {/* <!-- <a routerLink="/" >Home</a>                  
                            <a routerLink="/" >Find Property</a> --> */}
                  {!user && (
                    <React.Fragment>
                      <button
                        type="button"
                        style={{ marginRight: "5px" }}
                        className="btn btn-outline-primary btn-sm"
                        onClick={this.toggleLoginModal}
                      >
                        Login
                      </button>
                      <Link
                        to="/sign-up"
                        className="btn btn-outline-primary btn-sm"
                      >
                        Register
                      </Link>
                    </React.Fragment>
                  )}
                  {user && (
                    <div className="user-image">
                      <Dropdown alignRight>
                        <Dropdown.Toggle variant="" id="dropdown-basic">
                          <span>
                            <span className="text-danger">Welcome </span> &nbsp;
                            {(user && user.fname) || ""}
                          </span>
                          &nbsp;
                          <img
                            src={userImg}
                            className="rounded-circle p-cursor"
                            alt="user"
                            width="50px"
                          />
                        </Dropdown.Toggle>
                        <Dropdown.Menu>
                          {user && user.isAdmin && (
                            <Dropdown.Item href="/admin">
                              {/* <Link
                                to="/admin"
                                className="btn btn-light btn-block"
                              >
                              </Link> */}
                              Admin Dashboard
                            </Dropdown.Item>
                          )}
                          <Dropdown.Item>
                            <button
                              onClick={this.handleLogout}
                              className="btn btn-light btn-block"
                            >
                              Logout
                            </button>
                          </Dropdown.Item>
                        </Dropdown.Menu>
                      </Dropdown>
                    </div>
                    // <mat-menu #headerRytmenu="matMenu" xPosition="before">
                    //       <button routerLink="/users/dashboard" mat-menu-item>Dashboard</button>
                    //       <button *ngIf="userService.currentUser?.user.isAdmin" routerLink="/admin/dashboard" mat-menu-item>Admin</button>
                    //       <button (click)="loginService.logOut()" mat-menu-item>Logout</button>
                    //   </mat-menu>
                  )}
                </div>
              </div>
            </div>
          </div>
        </header>

        {/* ---------------------- LOGIN MODAL ----------------------------- */}
        <LoginModal
          toggle={loginModalToggle}
          toggleLoginModal={this.toggleLoginModal}
          setLoggedInUser={this.setLoggedInUser}
          {...this.props}
        />
        {/* ---------------------- LOGIN MODAL ----------------------------- */}
        {user && <Navbar navItems={navItems} />}
        <CommonUIAddons pageLoaderFlag={togglePageLoaderFlag} />

        {/* =================== ALERT MESSAGE =================== */}
        {alertNotification.status && (
          <div className="container mt-3">
            <Alert
              variant={alertNotification.variant}
              onClose={this.handleAlertDismiss}
              dismissible
            >
              {alertNotification.message}
            </Alert>
          </div>
        )}
        {/* =================== ALERT MESSAGE =================== */}
      </React.Fragment>
    );
  }
}

export const togglePageLoader = () => {
  togglePageLoaderFlag = !togglePageLoaderFlag;
};

export default Header;

// ANGULAR_CODE_BASE/src/app/common/components/header/header.component.ts
import { Component, OnInit, Input } from '@angular/core';
// , ViewChild
import { Router, ActivatedRoute } from '@angular/router';

import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { LoginService } from '../../services/login.service';
import { UserService } from '../../services/user.service';
import { LoginModalComponent } from '../login-modal/login-modal.component';
import { CommonService } from '../../services/common.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {


  constructor(
    private loginService: LoginService,
    private userService: UserService,
    private router: Router,
    private route: ActivatedRoute,
    private modalService: NgbModal,
    private commonService: CommonService
  ) { }

  openloginModal() {
    const modalRef = this.modalService.open(LoginModalComponent);
  }

  // ----- FORM

  headerDropdown: false;
  toggleMenuItems = false;

  // ------------- LOGIN

  // Main header alert message
  HeaderMessage = {
    type: '',
    message: ''
  }
  navItems = [
    { path: '/users/dashboard', name: 'Dashboard' },
    { path: '/property/new', name: 'Add New Property' },
    { path: '/property/search', name: 'Find Property' },
    { path: '/property/listing', name: 'My Listing' },
    { path: '/users/profile/edit', name: 'My Profile' }
  ];

  closeHeaderMessage() {
    this.HeaderMessage.message = '';
  }

  changeHeaderMessage(type, message) {
    console.log('changeHeaderMessage');

    this.HeaderMessage = { type: type, message: message }
    var self = this;
    setTimeout(function () {
      self.closeHeaderMessage();
    }, 5000);
  }

  pageloaderStatus: boolean = true;

  ngOnInit() {
    this.route.queryParamMap.subscribe((data) => {
      if (data.get('action') === 'signUpsuccess') {
        this.changeHeaderMessage('success', 'Congratulations, you have been successfully registered, login to continue');
        this.openloginModal();
      }
      else if (data.get('action') === 'logOut') {
        this.changeHeaderMessage('success', 'You have logged out successfully');
        this.openloginModal();
      }
      else if (data.get('action') === 'login') {
        this.changeHeaderMessage('success', 'Please login to continue');
        this.openloginModal();
      }
    });

    // HEADER MESSAGE
    this.commonService.HeaderMessage$.subscribe((data: any) => {
      if (data)
        this.changeHeaderMessage(data.type, data.message);
    });

    // Toggling Page Loader status
    this.commonService.togglePageLoader$.subscribe(data => this.pageloaderStatus = data);

    //isAdmin
    // if (this.userService.currentUser && this.userService.currentUser.user.isAdmin) {
    //   this.navItems = [
    //     { path: '/admin/dashboard', name: 'Dashboard' }
    //   ];
    // }
    // else {
    //   this.navItems = [
    //     { path: '/users/dashboard', name: 'Dashboard' },
    //     { path: '/users/property/new', name: 'Add New Property' },
    //     { path: '/users/property/search', name: 'Find Property' },
    //     { path: '/users/property/listing', name: 'My Listing' },
    //     { path: '/users/profile/edit', name: 'My Profile' }
    //   ];
    // }
  }



}

<header style="margin-bottom: 0px;" class="">
    <div class="container">
        <div class="row">
            <div class="col-md-4"> <img src="assets/images/Logo_SA.png" class="p-cursor" width="50px" alt="LOGO" routerLink="/"></div>
            <div class="col-md-8">
                <div class="header-ryt text-right">  
                    <!-- <a routerLink="/" >Home</a>                  
                    <a routerLink="/" >Find Property</a> -->
                    <button type="button" style="margin-right: 5px;" *ngIf="!loginService.isLoggedIn()" (click)="openloginModal()" class="btn btn-outline-primary btn-sm">Login </button>
                    <button type="button"routerLink="/users/sign-up" *ngIf="!loginService.isLoggedIn()" class="btn btn-outline-primary btn-sm">Register</button>
                    
                    <div *ngIf="loginService.isLoggedIn()">
                        <div class="user-image" >
                            <span><span class="text-danger" >Welcome</span> {{userService.currentUser.user.fname}} </span>
                            <img [matMenuTriggerFor]="headerRytmenu" src="assets/images/user.jpg" 
                                (click)="headerDropdown = !headerDropdown"
                            class="rounded-circle p-cursor" alt="user">
                        </div>
                        <mat-menu #headerRytmenu="matMenu" xPosition="before">
                            <button routerLink="/users/dashboard" mat-menu-item>Dashboard</button>
                            <button *ngIf="userService.currentUser?.user.isAdmin" routerLink="/admin/dashboard" mat-menu-item>Admin</button>
                            <button (click)="loginService.logOut()" mat-menu-item>Logout</button>
                        </mat-menu>
                        <!-- <ul *ngIf="headerDropdown" class="header-drp-dwn" >
                            <li><button (click)="headerDropdown = !headerDropdown"
                                class="btn btn-light btn-block">Dashboard</button></li>
                            <li *ngIf="userService.currentUser?.user.isAdmin" ><button routerLink="/admin/dashboard" class="btn btn-light btn-block">Admin</button></li>
                            <li><button (click)="headerDropdown = !headerDropdown"
                                 routerLink="/users/sign-up" (click)="loginService.logOut()"
                            class="btn btn-light btn-block">Logout</button></li>
                        </ul> -->
                    </div>
                    <!-- <button type="button" *ngIf="!loginService.isLoggedIn()" routerLink="/users/sign-up" (click)="loginService.logOut()" class="btn btn-outline-primary btn-sm">Logout</button> -->
                </div>
            </div>
        </div>
    </div>
</header>

<!-- ---------- NAV BAR ---------- -->

<nav *ngIf="loginService.isLoggedIn()" class="navbar navbar-expand-md bg-danger navbar-dash nav-dash">
    <!-- <a class="navbar-brand" href="#">Navbar</a> -->
    <button class="navbar-toggler" (click)="toggleMenuItems = !toggleMenuItems" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" [class.show-collapsed-menu]="toggleMenuItems" id="collapsibleNavbar">
        <div class="container">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" routerLink="/"><i class="fa fa-home" aria-hidden="true"></i> | </a>
            </li>
            <li *ngFor="let nav of navItems;" routerLink="{{nav.path}}" routerLinkActive="active" class="nav-item p-cursor">
                <a class="nav-link">{{ nav.name }}</a>
            </li>
        </ul>
        </div>
    </div>
</nav>

<!-- ---------- NAV BAR ---------- -->

<!-- ------------------ PAGE LOADER ---------------- -->
<app-small-components [componentName]="'barLoader'" [loaderActive] ="pageloaderStatus" ></app-small-components>
<!-- ------------------ PAGE LOADER ---------------- -->

<div *ngIf="HeaderMessage.message" class="container header-message">
    <div class="alert alert-{{HeaderMessage.type}}" >{{HeaderMessage.message}}
        <button type="button" class="close" (click)="closeHeaderMessage()" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>

<!-- <div class="fullPageLoaderMain">
    <div class="fullPageLoader">
        <mat-spinner [diameter]="150" ></mat-spinner>
    </div>
</div> -->
