// ANGULAR_CODE_BASE/src/app/features/home/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { map } from 'rxjs/operators';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/distinctUntilChanged';
import { UserService } from '../../../../common/services/user.service';
import { CommonService } from '../../../../common/services/common.service';
import { Router } from "@angular/router";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  images: Array<string>;
  cityList = [];
  propertyTypeList;
  searchPropData = { propertyFor: 'sell', location: '' };
  hideOwnProperty = false;

  constructor(
    private _http: HttpClient,
    private userService: UserService,
    private commonService: CommonService,
    private router: Router
  ) { }

  search = (text$: Observable<string>) =>
    text$
      .debounceTime(200)
      .distinctUntilChanged()
      .map(term => term.length < 2 ? [] : this.cityList.map(v => {
        return (v.name.toLowerCase().indexOf(term.toLowerCase()) > -1) ? v.name : ''
      }).filter(a => a).slice(0, 10));

  ngOnInit() {
    this._http.get('https://picsum.photos/list')
      .pipe(map((images: Array<{ id: number }>) => this._randomImageUrls(images)))
      .subscribe(images => {
        this.images = images;
      });

    this.commonService.getCitylist()
      .subscribe(response => {
        this.cityList = response;
        // response.forEach(element => {
        //   this.cityList.push(element.name);
        // });
      });

    this.commonService.getPropertyTypeList()
      .subscribe(response => {
        this.propertyTypeList = response;
      });

    this.hideOwnProperty = this.userService.currentUser && this.userService.currentUser.user._id ? true : false;
  }

  searchProp(value) {
    value.propertyFor = this.searchPropData.propertyFor;

    var queryParamsTemp: any = {
      propertyFor: value.propertyFor,
      type: value.type
    };

    queryParamsTemp.city = this.cityList.map(e => {
      return e.name == value.city ? e._id : ''
    }).filter(ele => ele);

    this.router.navigate(['/property/search'], {
      queryParams: queryParamsTemp //{ 'city': value.city, 'propertyFor': value.propertyFor, 'type': value.type }
    })
  }

  queryParams = '?status=available';

  private _randomImageUrls(images: Array<{ id: number }>): Array<string> {
    return [1, 2, 3].map(() => {
      const randomId = images[Math.floor(Math.random() * images.length)].id;
      return `https://picsum.photos/900/500?image=${randomId}`;
    });
  }

}

<div class="searchProp-cont">
  <ngb-carousel *ngIf="images">
    <ng-template *ngFor="let item of [0, 1, 2]" ngbSlide>
      <img [src]="images[item]" class="carousal-img" width="100%" alt="Random first slide">
      <!-- <div class="carousel-caption">
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div> -->
    </ng-template>
  </ngb-carousel>

  <div class="container searchProp">
    <!-- <h4 class="text-danger">Search Property:</h4>
    <hr class="hr"> -->

    <form #searchData="ngForm" (ngSubmit)="searchProp(searchData.value)">
      <ngb-tabset type="pills">
        <ngb-tab>
          <ng-template ngbTabTitle>
            <label (click)="searchPropData.propertyFor = 'sell'">BUY</label>
          </ng-template>
          <ng-template ngbTabContent>
          </ng-template>
        </ngb-tab>
        <ngb-tab>
          <ng-template ngbTabTitle>
            <label (click)="searchPropData.propertyFor = 'rent'">RENT</label>
          </ng-template>

          <ng-template ngbTabContent>
          </ng-template>
        </ngb-tab>
        <ngb-tab>
          <ng-template ngbTabTitle><label><b routerLink="/property/new">POST A PROPERTY</b></label></ng-template>
          <ng-template ngbTabContent>
          </ng-template>
        </ngb-tab>
      </ngb-tabset>
      <div class="text-center searchFields">
        <div class="form-group">
          <input id="typeahead-basic" placeholder="Enter a location" type="text" class="rounded-left" ngModel
            #location="ngModel" name="city" [value]="searchPropData?.location" [ngbTypeahead]="search" />

          <select ngModel #city="ngModel" style="width: auto;" name="type"
            class="custom-select searchType rounded-0 p-cursor">
            <option value="">Property Type</option>
            <option *ngFor="let type of propertyTypeList" [value]="type._id">{{ type.title }}</option>
          </select>

          <button class="btn btn-danger searchButton rounded-0 rounded-right">Search</button>
        </div>
      </div>
    </form>
  </div>
</div>

<div class="container">
  <div class="mar-top-40">
    <h4 class="text-danger">Recent Postings:</h4>
    <hr class="hr">
    <!-- <p>{{ searchPropData | json }}</p>
    <p>{{ cityList | json }}</p> -->

    <div ngbSlide>
      <app-propertylist [blockView]="true" [blockSize]="4" [hideOwnProperty]="hideOwnProperty"
        [queryParams]="queryParams"></app-propertylist>
    </div>
  </div>
</div>

// REACT_CODE_BASE/src/components/home/home.jsx
import React, { Component } from "react";
import { Carousel } from "react-bootstrap";
import PropertyList from "../common/propertyList";
import http from "../../services/httpService";

import "../../assets/styles/home.scss";

class Home extends Component {
  state = {
    images: []
  };

  componentDidMount() {
    this.getImages();
  }

  getImages = async () => {
    const { data: imgs } = await http.get("https://picsum.photos/list");
    const images = [1, 2, 3].map(() => {
      const randomId = imgs[Math.floor(Math.random() * imgs.length)].id;
      return `https://picsum.photos/900/500?image=${randomId}`;
    });
    this.setState({ images });
  };

  render() {
    const { images } = this.state;
    return (
      <React.Fragment>
        <div>
          <Carousel>
            {images.map(item => (
              <Carousel.Item key={item}>
                <img
                  width="100%"
                  className="d-block w-100"
                  src={item}
                  alt="First slide"
                />
                <Carousel.Caption>
                  <h3>First slide label</h3>
                  <p>
                    Nulla vitae elit libero, a pharetra augue mollis interdum.
                  </p>
                </Carousel.Caption>
              </Carousel.Item>
            ))}
          </Carousel>
        </div>
        <div className="container mt-5">
          <h4 className="text-danger">Recent Postings:</h4>
          <hr className="hr" />
          <PropertyList queryParams="?status=available" {...this.props} />
        </div>
      </React.Fragment>
    );
  }
}

export default Home;
