// ANGULAR_CODE_BASE/src/app/features/users/registration/registration.component.ts
import { Component, OnInit } from '@angular/core';

import { FormGroup, FormControl, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { CommonService } from '../../../common/services/common.service';
import { RegistrationValidators } from '../../../common/validators/registration.validators';
import { environment } from '@sa-environments/environment';


@Component({
  selector: 'app-registration',
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.css']
})
export class RegistrationComponent implements OnInit {

  constructor(
    private commonService: CommonService,
    private registrationValidators: RegistrationValidators,
    private http: HttpClient,
    private router: Router
  ) { }

  registrationForm = new FormGroup({
    fname: new FormControl('', [Validators.required]),
    lName: new FormControl('', [Validators.required]),
    email: new FormControl('', [Validators.email, Validators.required], this.registrationValidators.checkEmailAvailability.bind(this.registrationValidators)),
    phoneNo: new FormControl('', [Validators.required]),
    password: new FormControl('', [Validators.required]),
    cPassword: new FormControl('', [Validators.required]),
    state: new FormControl('', [Validators.required]),
    city: new FormControl('', [Validators.required]),
    pincode: new FormControl('', [Validators.required]),
    user_type: new FormControl('', [Validators.required])
  }, { validators: this.registrationValidators.passwordMatch }
  );

  mainErrorMessage = {
    type: '',
    message: ''
  }

  stateList;
  private cityList = [];

  ngOnInit() {
    this.commonService.togglePageLoaderFn(false);
    this.commonService.getStatelist()
      .subscribe(response => {
        if (response.length > 0) {
          this.stateList = response;
        }
      });
  }

  getCityList(stateId) {
    // console.log(' - stateID -- ', stateId);
    this.cityList = [];

    if (stateId != 0) {
      this.commonService.getCitylistByState(stateId)
        .subscribe(response => {
          // console.log('-- ', response['citylist']);
          // return response['statelist'];
          if (response.length > 0) {
            this.cityList = response;
          }
        });
    }
    else {
      this.cityList = [];
    }
  }

  registration(data) {
    console.log(data);
    // this.router.navigate(['/'],{
    //   queryParams: { action: 'signUpsuccess' }
    // });
    this.http.post(environment.BASE_URL + '/auth/user/register', data.value)
      .subscribe(response => {
        console.log('--- reg form -- ', response);
        if (response && response['message']) {
          this.router.navigate(['/'], {
            queryParams: { action: 'signUpsuccess' }
          });
        }
      },
        (error: Response) => {
          this.mainErrorMessage.type = 'danger';

          if (error.status === 400) {
            this.mainErrorMessage.message = 'Your request is invalid';
          }
          else if (error.status) {
            this.mainErrorMessage.message = 'Something went wrong';
          }
        });
  }

  log(data) {
    // console.log('--',data);
  }

  // --------  Get fields for Form
  get fname() {
    return this.registrationForm.get('fname');
  }
  get lName() {
    return this.registrationForm.get('lName');
  }
  get email() {
    return this.registrationForm.get('email');
  }
  get phoneNo() {
    return this.registrationForm.get('phoneNo');
  }
  get registrationPassword() {
    return this.registrationForm.get('password');
  }
  get registrationcPassword() {
    return this.registrationForm.get('cPassword');
  }
  get pincode() {
    return this.registrationForm.get('pincode');
  }
  get state() {
    return this.registrationForm.get('state');
  }
  get city() {
    return this.registrationForm.get('city');
  }
  get user_type() {
    return this.registrationForm.get('user_type');
  }

}

<div class="container mr-t-b-60">
    <h3>Fill the following details to register as a new user-</h3>
    <form class="" [formGroup]="registrationForm" (ngSubmit)="registration(registrationForm)" (change)="log(registrationForm)" >
        <div *ngIf="mainErrorMessage">
            <p class="alert alert-{{ mainErrorMessage.type }}">{{ mainErrorMessage.message }}</p>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <input type="text" [appInputFormat]="'singleWordFiltercapitalize'" formControlName="fname" class="form-control"  placeholder="Enter First Name" required>
                <small class="text-danger"
             *ngIf="fname.touched && fname.invalid"  >
            This field is required</small>
            </div>
            <div class="form-group col-md-6">
                <input type="text" [appInputFormat]="'singleWordFiltercapitalize'" formControlName="lName" class="form-control" placeholder="Enter Last Name" required>
                <!-- ngModel name="lName" #lName="ngModel" -->
                <small class="text-danger"
             *ngIf="lName.touched && lName.invalid"  >
            This field is required</small>
            </div>
            <!-- (change)="log(name)" -->
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <div class="input-with-icon">                    
                    <input type="email" formControlName="email" class="form-control" placeholder="Enter Email Address" required >
                    <span *ngIf="email.pending" class="input-icon"><i class="fa fa-spinner fa-spin fa-2x fa-fw" ></i></span>
                </div>
                <!-- ngModel name="email" fa-spin  #email="ngModel" (change)="log(email)"   -->
                <small class="text-danger"
                    *ngIf="email.touched && email.invalid"  >
                    <small *ngIf="email.errors.required" >This field is required</small>
                    <small *ngIf="email.errors.email" >Please enter a valid email address</small>
                    <small *ngIf="email.errors.checkEmailAvailability" >This email address is already taken</small>
                </small>
            </div>
            <div class="form-group col-md-6">
                <input formControlName="phoneNo" type="number" (change)="log(phoneNo)"  class="form-control remove-numbr-icn" maxlength="10" placeholder="Enter Phone Number" required >
                <!-- ngModel name="phoneNo" type="number" #phoneNo="ngModel" -->
                <small class="text-danger"
                    *ngIf="phoneNo.touched && phoneNo.invalid"  >
                This field is required</small>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <input  type="password" name="registrationPassword" formControlName="password"   class="form-control" placeholder="Enter Password" required > 
                <!-- ngModel #registrationPassword="ngModel" (change)="log(registrationPassword)" -->
                <small class="text-danger"
                    *ngIf="registrationPassword.touched && registrationPassword.invalid"  >
                This field is required</small>
            </div>
            <div class="form-group col-md-6">
                <input  type="password" name="registrationcPassword" formControlName="cPassword"  placeholder="Re-enter Password" class="form-control" required >
                <!-- ngModel #registrationcPassword="ngModel" (change)="log(registrationcPassword)"  -->
                <small class="text-danger"
                    *ngIf="registrationcPassword.touched && registrationcPassword.invalid"  >
                This field is required</small>

                <span class="text-danger"
                    *ngIf="registrationForm.errors && registrationcPassword.touched">    
                    <small *ngIf="registrationForm.errors.passwordMatch" > Password do not match</small>
                    <!-- registrationForm.status === 'INVALID' -->
                </span>                
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                    <!-- #cityList (change)="getCityList(cityList.value)" -->
                <select name="state" formControlName="state" (change)="getCityList(state.value)" class="custom-select">
                    <option value="">Select State</option>
                    <option *ngFor="let state of stateList" value="{{state._id}}">{{state.name}}</option>
                </select>
                <small class="text-danger"
                    *ngIf="state.touched && state.invalid"  >
                This field is required</small>
            </div>
            <div class="form-group col-md-4">
                <select name="city" formControlName="city" class="custom-select">
                    <option value="">Select City</option>
                    <option *ngFor="let city of cityList" value="{{city._id}}">{{city.name}}</option>
                </select>
                <small class="text-danger"
                    *ngIf="city.touched && city.invalid"  >
                This field is required</small>
            </div>
            <div class="form-group col-md-4">
                <input formControlName="pincode" type="text" name="pincode" placeholder="Enter PIN Code" class="form-control">
                <small class="text-danger"
                    *ngIf="pincode.touched && pincode.invalid"  >
                This field is required</small>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <strong>I am </strong> &nbsp;
                <label><input type="radio" formControlName="user_type" value="1" (change)="log(user_type)" name="user_type" checked> Buyer/Owner &nbsp; </label>
                <label><input type="radio" formControlName="user_type" value="2" (change)="log(user_type)" name="user_type"> Agent &nbsp; </label>
                <label><input type="radio" formControlName="user_type" value="3" (change)="log(user_type)" name="user_type"> Builder &nbsp; </label>
                <small class="text-danger"
                    *ngIf="user_type.touched && user_type.invalid"  >
                This field is required</small>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">                
                <button class="btn btn-success form-control" [disabled]="!registrationForm.valid" >Sign up</button>
            </div>
        </div>
        <!-- <p>{{ registrationForm.value | json }}</p>
        <p>{{ registrationForm.status | json }}</p>
        <p>{{ registrationForm.errors | json }}</p> -->
    </form>
</div>

// REACT_CODE_BASE/src/components/users/registration.jsx
import React from "react";
import Joi from "joi-browser";
import { Redirect } from "react-router-dom";

import Form from "./../common/form";
import * as commonService from "../../services/commonServices";

class Registration extends Form {
  state = {
    data: {
      fname: "",
      lName: "",
      email: "",
      phoneNo: "",
      password: "",
      cPassword: "",
      state: "",
      city: "",
      pincode: ""
    },
    errors: {},
    stateList: [],
    cityList: []
  };

  schema = {
    fname: Joi.string()
      .required()
      .label("First Name"),
    lName: Joi.string()
      .required()
      .label("Last Name"),
    email: Joi.string()
      .email()
      .required()
      .label("Email"),
    phoneNo: Joi.number()
      .required()
      .label("Phone Number"),
    password: Joi.string()
      .required()
      .label("Password"),
    cPassword: Joi.string()
      // .valid(Joi.ref("password"))
      .required()
      .label("Confirm Password"),
    // .options({ language: { any: { allowOnly: "password does not match" } } }),
    state: Joi.string()
      .required()
      .label("State"),
    city: Joi.string()
      .required()
      .label("State"),
    pincode: Joi.number()
      .required()
      .label("Pincode")
  };

  async componentDidMount() {
    try {
      const { data: stateList } = await commonService.get("/common/state");
      this.setState({
        stateList: [{ name: "--Select State--", _id: "" }, ...stateList]
      });
    } catch (error) {
      console.log("Error while fetching stateList: ", error);
    }
  }

  renderCityList = async stateId => {
    try {
      const { data: cityList } = await commonService.get(
        `/common/cities/${stateId}`
      );
      console.log("renderCityList ", cityList, stateId);
      this.setState({
        cityList: [{ name: "--Select City--", _id: "" }, ...cityList]
      });
    } catch (error) {
      console.log("Error while fetching cityList: ", error);
    }
  };

  validateUniqueEmail = async email => {
    try {
      const { data: result } = await commonService.get(
        `/common/checkemail-availability/email/${email}`
      );
      console.log({ result });
      const errors = this.state.errors;
      if (result && result.response) {
        errors["email"] = "This email address already exists";
      }
      this.setState({ errors });
    } catch (error) {
      console.log("Email availability error: ", error);
    }
  };

  doSubmit = async () => {
    console.log("---- ", this.state.data);
    const { password, cPassword } = this.state.data;
    if (password !== cPassword) {
      const errors = { cPassword: "Password does not match." };
      this.setState({ errors });
      return;
    }
    try {
      const { data: response } = await commonService.post(
        "/auth/user/register",
        this.state.data
      );
      console.log(response);
      if (response && response.message) {
        return this.props.history.push("/?action=signUpsuccess");
      }
    } catch (error) {
      console.log("Error in registration: ", error);
    }
  };

  render() {
    return (
      <React.Fragment>
        <div className="container mt-5 mb-5">
          <h3>Fill the following details to register as a new user-</h3>
          <form onSubmit={this.handleSubmit}>
            <div className="form-row">
              <div className="col-md-6">
                {this.renderInput(
                  "First Name",
                  "fname",
                  "input",
                  "Enter First Name"
                )}
              </div>
              <div className="col-md-6">
                {this.renderInput(
                  "Last Name",
                  "lName",
                  "input",
                  "Enter Last Name"
                )}
              </div>
            </div>
            <div className="form-row">
              <div className="col-md-6">
                {/* <div className="input-group">
                  <input
                    type="text"
                    className="form-control"
                    aria-label="Amount (to the nearest dollar)"
                  />
                  <div className="input-group-append">
                    <span className="input-group-text">$</span>
                    <span className="input-group-text">0.00</span>
                  </div>
                </div> */}
                {this.renderInput(
                  "Email Address",
                  "email",
                  "email",
                  "Enter Email Address",
                  "validateUniqueEmail"
                )}
              </div>
              <div className="col-md-6">
                {this.renderInput(
                  "Phone Number",
                  "phoneNo",
                  "number",
                  "Enter Phone Number"
                )}
              </div>
            </div>
            <div className="form-row">
              <div className="col-md-6">
                {this.renderInput(
                  "Password",
                  "password",
                  "password",
                  "Enter Password"
                )}
              </div>
              <div className="col-md-6">
                {this.renderInput(
                  "Confirm Password",
                  "cPassword",
                  "password",
                  "Re-enter Password"
                )}
              </div>
            </div>
            <div className="form-row">
              <div className="col-md-4">
                {this.renderSelect(
                  "State",
                  "state",
                  this.state.stateList,
                  "renderCityList"
                )}
              </div>
              <div className="col-md-4">
                {this.renderSelect("City", "city", this.state.cityList)}
              </div>
              <div className="col-md-4">
                {this.renderInput(
                  "Pincode",
                  "pincode",
                  "number",
                  "Enter pincode"
                )}
              </div>
            </div>
            <div className="form-row">
              <div className="col-md">
                <input
                  type="submit"
                  disabled={this.validate()}
                  className="btn btn-success form-control"
                  value="Sign up"
                />
              </div>
            </div>
          </form>
        </div>
      </React.Fragment>
    );
  }
}

export default Registration;
