// REACT_CODE_BASE/src/components/common/propertyList.jsx
import React, { Component } from "react";
// import { togglePageLoader } from "./header";

import { get, showGFSImage } from "../../services/commonServices";
import { getCurrentUser } from "../../services/authService";
import { connect } from "react-redux";

class PropertyList extends Component {
  state = {
    propertyList: [],
    queryParams: ""
  };

  componentDidMount() {
    this.getPropertyListings();
  }

  componentDidUpdate() {
    if (this.props.queryParams !== this.state.queryParams)
      this.getPropertyListings();
  }

  getPropertyListings = async () => {
    let { queryParams, userId, notUserId, listingCount } = this.props;
    const user = getCurrentUser();
    const queryTemp = this.props.queryParams;

    if (userId && user && user._id) {
      if (queryParams) queryParams += `&userId=${user._id}`;
      else queryParams = `?userId=${user._id}`;
    } else if (notUserId && user && user._id) {
      if (queryParams) queryParams += `&notUserId=${user._id}`;
      else queryParams = `?notUserId=${user._id}`;
    }
    // console.log({ user });

    // togglePageLoader();
    this.props.togglePageLoader(true);
    const { data: propertyList } = await get(`/property/filter${queryParams}`);
    this.props.togglePageLoader(false);
    // togglePageLoader();
    if (listingCount) {
      this.props.listingCount(propertyList.length);
    }
    this.setState({ propertyList, queryParams: queryTemp });
  };

  // openPropertyPage = slug => {
  //   return this.props.history.push(`/property/view/${slug}`);
  // };

  handleBtnClick = (e, type) => {
    if (type === 'rent' || type === 'sell') {
      e.preventDefault();
      e.stopPropagation();
    }
    else if (type === 'edit') return this.props.history.push(`/property/edit/${type}`);
    else return this.props.history.push(`/property/view/${type}`);
  };

  render() {
    const { propertyList } = this.state;
    let blockClasses = "col-md-4  mt-4";
    if (this.props.blockSize)
      blockClasses = `col-md-${this.props.blockSize}  mt-4`;

    return (
      <React.Fragment>
        {!propertyList.length && (
          <h4 className="text-center text-warning">No data found</h4>
        )}
        <div className="row">
          {propertyList.map(property => (
            <div
              onClick={(event) => this.handleBtnClick(event, property.slug)}
              key={property._id}
              className={blockClasses}
            >
              <div className="card clickable">
                <div className="row">
                  <div
                    className={this.props.blockSize === 12 ? "col-3" : "col-12"}
                  >
                    <img
                      src={showGFSImage(property.images[0])}
                      height="120px"
                      className="card-img-top"
                      alt="img"
                    />
                  </div>
                  <div
                    className={this.props.blockSize === 12 ? "col-7" : "col-12"}
                  >
                    <div className="card-body">
                      <h5
                        className={
                          this.props.blockSize === 12
                            ? "card-title"
                            : "card-title text-center"
                        }
                      >
                        {property.title}
                      </h5>
                      <ul
                        className={
                          this.props.blockSize === 12
                            ? "list-unstyled"
                            : "list-unstyled text-center"
                        }
                      >
                        <li>
                          <small>
                            {property.locality},
                            {property.city && property.city.name || ''},{" "}
                            {property.state && property.state.name || ''}
                          </small>
                        </li>
                        <li>
                          <small>
                            {property.type.title} <b>|</b> {property.updatedOn}{" "}
                          </small>
                        </li>
                      </ul>
                      <p className="card-text">{property.description}</p>
                    </div>
                  </div>
                  <div
                    className={this.props.blockSize === 12 ? "col-2" : "col-12 buttonContainer"}
                  >
                    <div
                      className={
                        this.props.blockSize === 12
                          ? "pt-2 text-left"
                          : "pb-2 text-center"
                      }
                    >
                      <button
                        onClick={event => this.handleBtnClick(event, "edit")}
                        className="btn btn-info btn-sm mt-2"
                      >
                        <small>Edit Property</small>
                      </button>
                      <button
                        onClick={event =>
                          this.handleBtnClick(event, property.propertyFor)
                        }
                        className="btn btn-success btn-sm mt-2 blockPropBtnMargn"
                      >
                        <small>
                          {property.propertyFor === "sell"
                            ? "Mark as sold"
                            : "Mark as acquired"}
                        </small>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </React.Fragment>
    );
  }
}

// const mapStateToProps = (state) => {
//   return {

//   }
// }

const handleReducers = dispatch => {
  return {
    togglePageLoader: value => dispatch({ type: "TOGGLE_PAGELOADER", value })
  };
};

export default connect(
  null,
  handleReducers
)(PropertyList);

// src/app/common/components/propertylist/propertylist.component.ts
import { Component, OnInit, Input, OnChanges } from '@angular/core';
import { Http } from '@angular/http';
import { CommonService } from '../../services/common.service';
// import { PropertyService } from '../../services/property.service';
import { LoginService } from '../../services/login.service';
import { UserService } from '../../services/user.service';

@Component({
  selector: 'app-propertylist',
  templateUrl: './propertylist.component.html',
  styleUrls: ['./propertylist.component.scss']
})
export class PropertylistComponent implements OnInit, OnChanges {

  constructor(
    private commonService: CommonService,
    private loginService: LoginService,
    private userService: UserService,
    // private propertyService: PropertyService
  ) { }

  // @Input('listType') listType: string;
  @Input('blockView') blockView = false;
  @Input('blockSize') blockSize = 12;
  @Input('queryParams') queryParams = '';
  @Input('hideOwnProperty') hideOwnProperty = false;

  propertyList = [];

  getPropertyList(params:any = ''){
    this.commonService.togglePageLoaderFn(true);
    if(this.hideOwnProperty && this.userService.currentUser.user._id) params = this.queryParams ? `${params}&notUserId=${this.userService.currentUser.user._id}` : `?notUserId=${this.userService.currentUser.user._id}`;
    console.log('final query ', params);
    this.commonService.filterProperties(params)
      .subscribe((result: any) => {
        if(result) this.propertyList = result;               
        console.log('propertyList: ', this.propertyList);
      }, (err) => console.log({err}),
    () => this.commonService.togglePageLoaderFn(false) );
      
  }

  ngOnInit() {
    this.getPropertyList(this.queryParams);
  }

  ngOnChanges() {    
    this.getPropertyList(this.queryParams);
  }

}

<div class="row">
  <div *ngFor="let property of propertyList" class="col-md-{{blockSize}} pad-btm-15" >
  <!-- [ngClass]="{
    'col-md-12': !blockView,
    'col-md-6': blockView
  }"> -->
    <div class="border-main mar-ryt-15">
      <div class="row border-box-manage property-box">
        <div [ngClass]="{
          'col-md-3 border-right': !blockView,
          'col-md-12 border-bottom': blockView
        }" class="">image</div>
        <div  [ngClass]="{
          'col-md-7': !blockView,
          'col-md-12 text-center': blockView
        }" class="">
          <h5>{{property.title}}</h5>
          <ul style="padding-left: 0px;" class="propertyLocation">
            <li><small>{{property.locality}}, {{property.city.name}}, {{property.state.name}}</small></li>
            <li>{{property.type.title}} | {{ property.updatedOn | date:'fullDate' }}</li>
          </ul>
          <p>{{property.description}}</p>
        </div>
        <div *ngIf="loginService.isLoggedIn() && property?.userId?._id == userService?.currentUser?.user?._id" [ngClass]="{
            'col-md-2': !blockView,
            'col-md-12 text-center': blockView
          }">
          <!-- <small class="float-right" >{{ property.updatedOn | date:'fullDate' }}</small>  -->
          <!-- <button [class.btn-block]="!blockView" class="btn btn-primary btn-sm">View Property</button> -->
          <button [class.btn-block]="!blockView" routerLink="/users/property/edit/{{property._id}}" class="btn btn-info btn-sm">Edit Property</button>
          <button [class.btn-block]="!blockView" class="btn btn-success btn-sm">
            <span (click)="propertyService.markProperty('sold')" *ngIf="property.propertyFor == 'sell'" >Mark as Sold</span>
            <span (click)="propertyService.markProperty('rented')" *ngIf="property.propertyFor == 'rent'" >Mark as Acquired</span>
          </button>
        </div>
      </div>
    </div>    
  </div>
</div>
<div>
  <h4 *ngIf="propertyList.length <= 0" class="text-center text-warning" >No data found</h4>
</div>
